{
 "title": "Dashboard Principal",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "nb_cpu",
    "query": {
     "query": "query_result(machine_cpu_cores)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hôte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nombre de CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nb disques",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_disk_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mémoire disponible",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"user\"}[30s])) ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lecture / Ecriture du disque",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "Lecture"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "Ecriture"
    }
   ]
  },
  {
   "title": "Nb CPU utilisés par seconde",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "round(sum(rate(node_cpu_seconds_total[1m])))",
     "legendFormat": "Nb CPU"
    }
   ]
  },
  {
   "title": "Usage de la RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes[1m]))",
     "legendFormat": "Usage Total"
    },
    {
     "expr": "sum(rate(container_memory_working_set_bytes[1m]))",
     "legendFormat": "Usage Réel (cache exclu)"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Uptime (disponibilité des conteneurs)",
   "type": "stat",
   "description": "Temps écoulé depuis le redémarrage du dernier container",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - container_start_time_seconds{name=~\".+\", container_label_com_docker_compose_project=\"projet_fraud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mémoire utilisée par les containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", container_label_com_docker_compose_project=\"projet_fraud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage CPU par les containers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\", container_label_com_docker_compose_project=\"projet_fraud\"}[1m]))*100 / $nb_cpu",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage de la RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\",container_label_com_docker_compose_project=\"projet_fraud\"}[1m])) by (name) /1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage RAM par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\", container_label_com_docker_compose_project=\"projet_fraud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation du CPU en % (par conteneur)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container_label_com_docker_compose_project=\"projet_fraud\"} [1m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage de la RAM par les containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{name=~\".+\", container_label_com_docker_compose_project=\"projet_fraud\"}[1m]))",
     "legendFormat": "Usage Total"
    },
    {
     "expr": "sum(rate(container_memory_working_set_bytes{name=~\".+\", container_label_com_docker_compose_project=\"projet_fraud\"}[1m]))",
     "legendFormat": "Usage Réel (cache exclu)"
    }
   ]
  },
  {
   "title": "Trafic réseau entrant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",container_label_com_docker_compose_project=\"projet_fraud\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic réseau sortant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{image!=\"\",container_label_com_docker_compose_project=\"projet_fraud\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}