{
 "title": "Dashboard Fraude",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nombre moyen de transactions par seconde",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(http_requests_total{handler=\"/predict\", job=\"api-recepteur\", method=\"POST\", status=\"2xx\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de transactions échouées erreurs par seconde",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"api-recepteur\", status=\"4xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taille moyenne des requêtes HTTP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_size_bytes_count{handler=\"/predict\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durée moyenne par requête HTTP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{handler=\"/predict\"}[1m])) / sum(rate(http_request_duration_seconds_count{handler=\"/predict\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taille moyenne des réponses HTTP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_count{handler=\"/predict\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}