{
 "title": "Détails par container",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "container", "label": "Nom du conteneur docker", "query": { "query": "label_values(name)" } },
   {
    "name": "nb_cpu",
    "query": {
     "query": "query_result(machine_cpu_cores)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime ($container)",
   "type": "stat",
   "description": "Temps écoulé depuis le dernier redémarrage du conteneur",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (time() - container_start_time_seconds{name=\"$container\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage CPU ($container)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"$container\"}[1m]))*100 / $nb_cpu",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage de la RAM ($container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{name=\"$container\"}[1m]))",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{name=\"$container\"}[1m])) - sum(rate(container_memory_working_set_bytes{name=\"$container\"}[1m]))",
     "legendFormat": "Cache"
    }
   ]
  },
  {
   "title": "Trafic réseau ($container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"$container\"}[1m]))",
     "legendFormat": "Trafic entrant"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"$container\"}[1m]))",
     "legendFormat": "Trafic sortant"
    }
   ]
  }
 ]
}